### ISSUE TITLE
Name von Porky

### ISSUE THREAD

**Issue by GlostU** [Madokamiiiiii/Mother3German#19]
@Madokamiiiiii 
Hi, ich weiß gerade nicht, wo ich dir Feedback senden kann, also habe ich einfach ein neues Issue eröffnet.
Habe eben mal dein Projekt überflogen und gesehen, dass du Porky mit Pokey übersetzt.
Hat das einen bestimmten Grund? Denn offiziell wird er im deutschen Porky genannt, wenn man sich die Smash Trophäen anguckt.

In meiner deutschen Übersetzung von EarthBound nenne ich ihn auch Porky, ich würde es besser finden, wenn dann der Name gleich bleibt. Dann gibt es weniger Verwirrung.
Ist aber natürlich deine Entscheidung.

**Comment by Madokamiiiiii** [comment]
Das ist tatsächlich eine Sache, über das ich mir mal vor einiger Zeit den Kopf zerbrochen habe, denn mir sind beide Namen geläufig. Offiziell sind auch beide Namen legitim, je nachdem wie man das japanische romanisiert.

Ich habe aber das Gefühl, dass im deutschen Raum Pokey bekannter ist als Porky, was wohl vor allem an der vorhandenen deutschen EarthBound-Übersetzung liegt. Ich werd das aber nochmal überdenken, wenn ich mit dem Skript durch bin. Vermutlich bin ich etwas voreingenommen, da ich vor Mother 3 immer nur Pokey kannte. 
Letztendlich sind es aber nur ein paar Klicks, um den Namen zu ändern.

Danke für das Feedback.

**Comment by Madokamiiiiii** [comment]
Hab das nun nochmal evaluiert und mich entschieden, den netten Kerl Porky zu nennen. Dürfte nun mittlerweile an allen Stellen richtig stehen. Ich pinge das Issue mal an, da bestimmt noch mehr darauf stolpern könnten.
