### ISSUE TITLE
Grafiken übersetzen

### ISSUE THREAD

**Issue by Madokamiiiiii** [Madokamiiiiii/Mother3German#21]
Animierte Texte wie der Text zu Beginn von Kapitel 4 lassen sich nicht leicht editieren.
Übliche Programme scheinen nicht zu funktionieren. Vielleicht sind sie speziell komprimiert oder eine bestimmte Einstellung muss angepasst werden?

Aufgrund von Platzmangel ist es auch nicht leicht das Hauptmenü zu übersetzen.

**Comment by Madokamiiiiii** [comment]
Der Text von Kapitel 4 lässt sich übersetzen, jedoch nur relativ nervenaufreibend. Ursache war eine korrupte Datei.

**Comment by Madokamiiiiii** [comment]
![3yearslater](https://user-images.githubusercontent.com/7693897/89741545-73bbf680-da92-11ea-8e62-01080a1d822b.png)
Falls jemand Lust hat

**Comment by GlostU** [comment]
![Years_later](https://user-images.githubusercontent.com/38181751/90184148-f4d9fd00-ddb4-11ea-8f9e-090725018481.png)
Habe mich mal darangesetzt. Kannst dann ja die letzen Feinschliffe machen.

**Comment by Madokamiiiiii** [comment]
Aus irgendeinem Grund war die Palette bei der Datei ganz komisch. Mit etwas Arbeit in GIMP passt es aber. Muss ich nur noch die Border hinzufügen und die Wörter Tazmily und Dorf tauschen, damit es konsistent mit dem Skript bleibt.
Danke sehr.

**Comment by Madokamiiiiii** [comment]
Im Repository gibt es nun einen Ordner "extraGraphics". Darin enthalten sind alle Grafiken (die ich finden konnte) mit den jeweiligen Offsets in der ROM.

**Comment by Madokamiiiiii** [comment]
All graphics are now translated
