### ISSUE TITLE
YouWon gfx

### ISSUE THREAD

**Issue by GlostU** [Madokamiiiiii/Mother3German#24]
Ich fande die "Sieg!" Grafik nicht ganz so hübsch und habe mal meine eigene Version erstellt.
Vielleicht gefällt sie dir ja auch:
[gfx_GEWONNEN.zip](https://github.com/Madokamiiiiii/Mother3German/files/5071308/gfx_GEWONNEN.zip)

**Comment by Madokamiiiiii** [comment]
Gefällt mir sehr gut, ist aufgenommen. Ich tue mir tatsächlich schwer damit, die Bilddateien zu editieren, insbesondere mit den Limitierungen.
