### ISSUE TITLE
Soundplayer ist kaputt.

### ISSUE THREAD

**Issue by Clainekun** [Madokamiiiiii/Mother3German#25]
Moin moin,

wenn man versucht, den Soundplayer im Titelbildschirm aufzurufen, hängt sich das Spiel mit nem Blackscreen auf. Wurden die Liedtitel nicht übersetzt oder ist das nen größeres Problem? Oder bin ich der einzige mit dem Problem? xD

MFG
Claine
![Screenshot_1](https://user-images.githubusercontent.com/75849924/101923255-77da5b00-3bcf-11eb-8a9f-73b4f0dea561.png)
![Screenshot_2](https://user-images.githubusercontent.com/75849924/101923261-79a41e80-3bcf-11eb-8305-3a80337b11ff.png)

**Comment by Madokamiiiiii** [comment]
Bug ist reproduzierbar.

Puh, scheint sich um einen hartnäckigen Bug zu handeln. Ein Test mit den englischen Dateien führt zum selben Ergebnis.
Ich bin mir sicher, dass es mal funktioniert hat und finde das daher etwas komisch.

Danke für die Meldung.

**Comment by Madokamiiiiii** [comment]
The game tries to jump to an invalid address

**Comment by Madokamiiiiii** [comment]
Fixed. The psi descriptions were too long and overwrote the sound player.
