### ISSUE TITLE
The patch doesn't work. / Der Patch funktioniert nicht.

### ISSUE THREAD

**Issue by Johnephen** [Madokamiiiiii/Mother3German#37]
Hallo, ich wollte den Patch verwenden und habe es genauso, wie es in der Erklärung unter Kompilieren beschrieben wurde ausgeführt und es klappt nach wiederholten versuchen noch immer nicht. darum wollte ich fragen, was genau ich Falsch mache. Ich habe den Prozess, wie ich es kompilieren soll oder was ich unter der Erklärung verstanden habe, dieses Video aufgenommen und hoffe, es ist erkennbar, was das Problem ist.

Link: https://youtu.be/bXllPnUSACM

**Comment by Madokamiiiiii** [comment]
Zum Kompilieren fehlen zwei Dinge:
1. Fehlt eine .dll-Datei, die ich vergessen habe mit hochzuladen. Die ist jetzt mit im Repo. Also nochmal neu herunterladen, dann ist sie da.
2. Auf deinem System muss das Programm Python installiert sein https://www.python.org/downloads/
Auch hier mein Fehler, dass ich das in der ReadMe nicht reflektiert habe.

**Comment by Madokamiiiiii** [comment]
Ansonsten ginge das auch mit dem Release hier: https://github.com/Madokamiiiiii/Mother3German/releases/tag/v1.0

Da fehlen lediglich ein paar vereinzelte Script Fixes

**Comment by Johnephen** [comment]
Ich werde es sofort ausprobieren und vielen Dank für das so schnelle antworten.
Sobald es klappt, werde ich mich melden. Und bei Problemen halt auch... aber schon mal voraus, vielen Dank.

**Comment by Johnephen** [comment]
Es Klappt! Und ich bin auch unglaublich froh darüber. Vermutlich lag es wirklich an der fehlenden Datei, aber ich Installierte auch Python noch bevor ich es ausprobierte. Dennoch vielen Dank und es ist unglaublich, dass du das gepackt hast.
