### ISSUE TITLE
[Not directly revelant for this project]Adding this Translateproject to https://www.romhacking.net/translations/

### ISSUE THREAD

**Issue by DiamantTh** [Madokamiiiiii/Mother3German#38]
Hello,
Does it make sense to add this project to the site mentioned below?
Found on your profile no way to contact you directly.

https://www.romhacking.net/translations/

Greetings

**Comment by Madokamiiiiii** [comment]
Hi,

just submitted an entry to the site.

**Comment by Madokamiiiiii** [comment]
Submission passed.
https://www.romhacking.net/translations/6528/
