### ISSUE TITLE
Unübersetzt

### ISSUE THREAD

**Issue by Immortalfafnir** [Madokamiiiiii/Mother3German#39]
In Kapitel 7, im Chimera Labor gibt es beim Eingang eine Person welche Items verkauft. Die Beschreibung eines Items ist nicht übersetzt. Ich wäre sehr erfreut wenn dieses Problem behoben werden könnte
![Screenshot_20220727-231424_RetroArch Plus](https://user-images.githubusercontent.com/110134519/181376725-ec9821fd-5144-40ed-842d-0a14d7c6f818.jpg)

**Comment by Madokamiiiiii** [comment]
Jo, hab ich übersehen. Vielen Dank fürs Melden.
 Mit https://github.com/Madokamiiiiii/Mother3German/commit/3ddcae8945f1e7443bca45e098bc4f4722c592d2 gefixt.
