### ISSUE TITLE
Naming Screen

### ISSUE THREAD

**Issue by Madokamiiiiii** [Madokamiiiiii/Mother3German#6]
Naming Screen besitzt keine Sonderzeichen. (und kann man ohne GBA-Programmierkenntnisse nicht beheben)

**Comment by Ksfreak** [comment]
Hallo Madokami mir ist eine fehlende übersetzung aufgefallen (es fehlt eine deutsche Übersetzung)!!! Das ist nähmlich der Debug Raum/Room da ist nähmlich alles noch auf Englisch (oder Japanisch)!? Wenn du das da noch beheben kannst!!! Brauchst du den Cheat Code dafür der lautet wie folgt!!!
CA1D8DB3 689FDAFA
9CC263F2 68DE0537
1DCAC2C5 4FCA9184
ansonsten ist alles gut übersetzt (meinung am Anfang des Spiels)
Hier ist ansonsten noch ein Bild zum Debug Room/Raum!!!
![Debug Room](https://user-images.githubusercontent.com/80100451/110107806-abcab400-7dab-11eb-8eab-367529678a46.png)

**Comment by Ksfreak** [comment]
Ach ja und ich habe noch vergessen zu schreiben!!! Wenn du in den Debug Raum/Room gelangen möchtest!?
Musst du erst den Cheat aktiviert haben und einmal Die L-Taste Oben gedrückt halten und dann in einem anderen Raum gehen!
Dann bist du im Debug Raum/Room!!!

**Comment by Madokamiiiiii** [comment]
Ist bekannt.
Weil dieser Raum durch das normale Spielen nicht erreicht werden kann, habe ich ihn (wie es üblich ist) erstmal nicht übersetzt

**Comment by Madokamiiiiii** [comment]
Naming Screen now contains special characters.
